password_box_image = Image("box-password.png");
password_box_sprite = Sprite(password_box_image);
password_box_sprite.SetPosition((screen_width / 2) - (password_box_image.GetWidth() / 2), password_box_y, 29);

password_image = Image.Text("Enter your password", 1.0, 1.0, 1.0, 1.0, theme_font);
password_sprite = Sprite(password_image);
password_sprite.SetPosition((screen_width / 2) - (password_image.GetWidth() / 2), password_text_y, 30);

fun display_password_callback(prompt, bullets) {
  password_mask = "";
  for (index = 0; index < bullets; index++) {
    password_mask += "*";
  }

  password_image = Image.Text(password_mask, 1.0, 1.0, 1.0, 1.0, theme_font);
  password_sprite.SetImage(password_image);
  password_sprite.SetPosition((screen_width / 2) - (password_image.GetWidth() / 2), password_text_y, 30);
}

Plymouth.SetDisplayPasswordFunction(display_password_callback);
