<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <RuntimeIdentifier>linux-x64</RuntimeIdentifier>
        <AssemblyName>oparch-install</AssemblyName>
        <RootNamespace>IOKode.OpinionatedArch.Installer</RootNamespace>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PublishSingleFile>true</PublishSingleFile>
        <SelfContained>true</SelfContained>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Terminal.Gui" Version="2.4.17"/>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\CommandLine\CommandLine.csproj"/>
        <ProjectReference Include="..\SpectreConsole\SpectreConsole.csproj"/>
    </ItemGroup>
    <ItemGroup>
        <AssemblyAttribute Include="System.Runtime.Versioning.SupportedOSPlatformAttribute">
            <_Parameter1>linux</_Parameter1>
        </AssemblyAttribute>
    </ItemGroup>
    <PropertyGroup>
        <BundleOutputDirectory>$(MSBuildThisFileDirectory)..\..\artifacts\opinionatedarch\</BundleOutputDirectory>
        <BundleAssetSourceDirectory>$(MSBuildThisFileDirectory)..\..\assets\</BundleAssetSourceDirectory>
        <BundleBinSourceDirectory>$(MSBuildThisFileDirectory)..\..\bin\</BundleBinSourceDirectory>
    </PropertyGroup>
    <Target Name="Bundle" DependsOnTargets="Publish">
        <ItemGroup>
            <BundleAssetFiles Include="$(BundleAssetSourceDirectory)**\*"/>
            <BundleBinFiles Include="$(BundleBinSourceDirectory)**\*"/>
        </ItemGroup>
        <RemoveDir Directories="$(BundleOutputDirectory)"/>
        <MakeDir Directories="$(BundleOutputDirectory);$(BundleOutputDirectory)assets;$(BundleOutputDirectory)bin"/>
        <Copy SourceFiles="$(PublishDir)$(AssemblyName)" DestinationFolder="$(BundleOutputDirectory)"/>
        <Copy SourceFiles="@(BundleAssetFiles)" DestinationFiles="@(BundleAssetFiles->'$(BundleOutputDirectory)assets/%(RecursiveDir)%(Filename)%(Extension)')"/>
        <Copy SourceFiles="@(BundleBinFiles)" DestinationFiles="@(BundleBinFiles->'$(BundleOutputDirectory)bin/%(RecursiveDir)%(Filename)%(Extension)')"/>
        <Exec Command="chmod 755 &quot;$(BundleOutputDirectory)$(AssemblyName)&quot;"/>
        <Exec Command="chmod -R u=rwX,go=rX &quot;$(BundleOutputDirectory)assets&quot;"/>
        <Exec Command="chmod 755 &quot;$(BundleOutputDirectory)bin/&quot;*"/>
    </Target>
</Project>
