#!/bin/bash

build() {
  add_runscript
  add_file '/usr/lib/locale/locale-archive'
  add_file '/usr/share/locale/nl/LC_MESSAGES/plymouth.mo'
}

help() {
  cat <<HELPEOF
Sets UTF-8 locale variables before Plymouth starts in initramfs.
HELPEOF
}
