#!/bin/bash

build() {
  add_file '/usr/share/fonts/opinionatedarch/OpenSans.ttf' '/usr/share/fonts/Plymouth.ttf'
}

help() {
  cat <<HELPEOF
Adds the bundled Open Sans Plymouth font explicitly to initramfs.
HELPEOF
}
